server:
  port: 8080
spring:
  application:
    name: userrestapi
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.102:8761/eureka/