server:
  port: 9090
spring:
  application:
    name: userservice
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.102:3306/user
    username: root
    password: 12345678
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.102:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.102


fromEmail: ccx997t3@163.com





